name: desktop_auth0_flutter
description: Generic auth0 implementation for the app, to support linux and windows
version: 0.1.0
homepage: https://github.com/Vild/flutter_pkgs

resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  app_links: ^6.4.1
  auth0_flutter: ^1.13.0
  auth0_flutter_platform_interface: ^1.13.0
  dart_jsonwebtoken: ^3.2.0
  flutter_secure_storage: ^9.2.4
  oauth2: ^2.0.3
  synchronized: ^3.4.0
  uri_scheme_registration: ^0.1.0
  url_launcher: ^6.3.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
